server:
  port: 8094
spring:
  profiles: product
  application: 
    name: exam-service
  datasource:
    url: jdbc:mysql://10.7.201.2:3306/exam?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:custhitachi123--}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
  redis:
    host: ${REDIS_HOST:10.7.201.2}
    port: ${REDIS_PORT:6379}
    maxIdle: 300
    maxActive: 600
    maxWait: 1000
    testOnBorrow: true
  rabbitmq:
    host: ${RABBIT_HOST:10.7.201.2}
    port: ${RABBIT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:joker}
    password: ${RABBITMQ_DEFAULT_PASS:custhitachi}
#  boot:
#    admin:
#      client:
#        url: http://${ADMIN_HOST:localhost}:${ADMIN_PORT:9186}/admin
#        username: ${ADMIN_USERNAME:admin}
#        password: ${ADMIN_PASSWORD:11}
#        instance:
#          service-base-url: http://${EXAM_SERVICE_HOST:localhost}:${server.port}
#          metadata:
#            tags:
#              environment: product
# mybatis 配置
mybatis:
  type-aliaes-package: org.example.examservice.model
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
  mapper-location: classpath:mapper/*.xml

#pagehelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 系统配置
sys:
  cacheExpire: 86400

# hystrix配置
hystrix:
  shareSecurityContext: true
  command:
    default:
      excution:
        ioslation:
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

cluster:
  workId: ${CLUSTER_WORKID:1}
  dataCenterId: ${CLUSTER_DATA_CENTER_ID:1}
